Repository Taka1304/egh-team20, pull requests merged in 2025-02, with the labels that each got.

#7 Hono API sampleの実装
  .env.example
  bun.lockb
  package.json
  src/app/api/[[...route]]/route.ts
  src/app/api/[[...route]]/sample/index.ts
  src/lib/env.ts
  src/lib/hono.ts
Labels: enhancement

#61 #31 日報詳細取得 API実装
  prisma/schema.prisma
  src/app/api/[[...route]]/reports/index.ts
Labels: ⚡️Backend

#64 #32 日報更新 API 実装
  src/app/api/[[...route]]/reports/index.ts
  src/app/api/[[...route]]/utils/index.ts
Labels: ⚡️Backend

#78 Feature/33 34
  src/app/api/[[...route]]/reports/index.ts
  src/app/api/[[...route]]/reports/reaction.ts
  src/app/api/[[...route]]/reports/utils.ts
Labels: ⚡️Backend

#106 ✨ 下書き一覧取得API実装
  src/app/api/[[...route]]/reports/index.ts
Labels: ⚡️Backend

#119 #29 TL用API実装
  src/app/api/[[...route]]/reports/index.ts
  src/app/api/[[...route]]/reports/reaction.ts
Labels: ✨enhancement, ⚡️Backend

#125 ✨ リアクションの情報を追加
  src/app/api/[[...route]]/reports/index.ts
Labels: ✨enhancement, ⚡️Backend

#130 ✨ 日報削除 API 実装
  src/app/api/[[...route]]/reports/index.ts
Labels: ⚡️Backend

#142 ✨ /reactions get実装
  src/app/api/[[...route]]/reactions/index.ts
  src/app/api/[[...route]]/route.ts
Labels: ⚡️Backend

#147 リダイレクト処理追加、サインアウト実装
  src/app/_features/Login/LoginView.tsx
  src/app/_features/Navigate/Header/UserMenu/UserMenu.tsx
Labels: 🐛bug, 🌐Frontend

#153 🐛 画像が表示されない件を修正
  src/app/_features/MarkdownContent/MarkdownContent.tsx
Labels: 🐛bug, 🌐Frontend

#156 リアクション機能をDBとつないだ
  src/app/_features/ReportCard/ReportCard.tsx
  src/app/_features/ReportCard/ReportCardView.tsx
  src/app/_features/Timeline/Timeline.tsx
  src/app/api/[[...route]]/reports/reaction.ts
  src/app/hooks/useReaction.ts
  src/app/hooks/useReprots.ts
  src/app/types/reports.ts
Labels: 🌐Frontend, 💄UI

#157 🗃️ badge機能実装、schema変更
  prisma/migrations/20250227105429_badge/migration.sql
  prisma/migrations/20250227114335_badge_del_updatedat/migration.sql
  prisma/schema.prisma
Labels: ⚡️Backend

#172 ✨ Badgeの情報を反映
  src/app/api/[[...route]]/badges/index.ts
  src/app/api/[[...route]]/route.ts
  src/app/api/[[...route]]/users/index.ts
Labels: ⚡️Backend

#193 通知機能の実装
  prisma/migrations/20250228062828_notification/migration.sql
  prisma/migrations/20250228082431_notification_report/migration.sql
  prisma/schema.prisma
  src/app/_features/NotificationModal/NotificationModal.tsx
  src/app/_features/NotificationModal/NotificationModalView.tsx
  src/app/_features/NotificationModal/useNotifications.tsx
  src/app/api/[[...route]]/notifications/index.ts
  src/app/api/[[...route]]/reports/reaction.ts
  src/app/api/[[...route]]/route.ts
  src/app/api/[[...route]]/users/index.ts
  src/lib/env.ts
  src/lib/supabase.ts
  src/lib/supabaseClient.ts
Labels: ✨enhancement, ⚡️Backend, 🌐Frontend, :fire: 優先度高

#195 通知バグ修正
  src/app/api/[[...route]]/reports/reaction.ts
  src/app/api/[[...route]]/users/index.ts
Labels: 🐛bug, ⚡️Backend

#201 ✨ /users/:id/contributions を実装
  src/app/api/[[...route]]/users/index.ts
Labels: ✨enhancement, ⚡️Backend

#212 #108 onboarding, interest周りの処理改善、authのsession情報改善
  bun.lockb
  next-auth.d.ts
  package.json
  src/app/_features/NotificationModal/NotificationModalView.tsx
  src/app/_features/OnboardingDialog/OnboardingDialog.tsx
  src/app/_features/OnboardingDialog/OnboardingDialogView.tsx
  src/app/_features/OnboardingDialog/index.tsx
  src/app/_features/OnboardingDialog/useOnboardingDialog.ts
  src/app/_features/Profile/ProfileCard/ProfileCard.stories.tsx
  src/app/_features/Profile/ProfileEditDialog/InterestsCategoryDropdown.tsx
  src/app/_features/Profile/ProfileEditDialog/ProfileEditDialog.tsx
  src/app/_features/Profile/ProfileRecommendedUsers/ProfileRecommendedUsersCard/ProfileRecommendedUserCard.tsx
  src/app/api/[[...route]]/interests/index.ts
  src/app/api/[[...route]]/users/index.ts
  src/app/hooks/useInterests.ts
  src/app/hooks/useUser.ts
  src/app/page.tsx
  src/lib/auth.ts
Labels: 🐛bug, ✨enhancement, ⚡️Backend, 🌐Frontend, ♻️ Refactor, 💄UI, :fire: 優先度高

#225 Aboutページの作成
  src/app/_features/About/Feature.tsx
  src/app/_features/About/Hero.tsx
  src/app/_features/About/TargetAudience.tsx
  src/app/_features/About/ValueProposition.tsx
  src/app/about/page.tsx
  src/app/layout.tsx
Labels: 🌐Frontend, 💄UI

#231 通知の表示名バグ修正
  src/app/_features/NotificationModal/NotificationModalView.tsx
  src/app/_features/NotificationModal/useNotifications.tsx
  src/app/api/[[...route]]/notifications/index.ts
  src/app/api/[[...route]]/reports/reaction.ts
  src/app/api/[[...route]]/users/index.ts
Labels: 🐛bug, ⚡️Backend, 🌐Frontend
